#ifdef __cplusplus
extern "C" {
#endif


#ifndef RSOD_GO_H
#define RSOD_GO_H

/* This file was automatically generated by cbindgen. Do not modify by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct ArrowSchema FFI_ArrowSchema;
typedef struct ArrowArray FFI_ArrowArray;

static inline struct ArrowSchema *to_arrow_schema(void *p) { return (struct ArrowSchema *)p; }
static inline struct ArrowArray *to_arrow_array(void *p) { return (struct ArrowArray *)p; }


#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

bool outlier_fit_predict(FFI_ArrowSchema *data_schema,
                         FFI_ArrowArray *data_array,
                         const char *_options_json,
                         FFI_ArrowSchema *result_schema,
                         FFI_ArrowArray *result_array);

bool baseline_fit_predict(FFI_ArrowSchema *data_schema,
                          FFI_ArrowArray *data_array,
                          FFI_ArrowArray *history_array,
                          FFI_ArrowSchema *history_schema,
                          const char *_options_json,
                          FFI_ArrowSchema *result_schema,
                          FFI_ArrowArray *result_array);

/**
 * FFI 函数：初始化数据库
 * 供 Go 代码在启动时显式调用
 */
bool rsod_storage_init(const char *path);

bool rsod_forecaster(FFI_ArrowSchema *data_schema,
                     FFI_ArrowArray *data_array,
                     FFI_ArrowArray *history_array,
                     FFI_ArrowSchema *history_schema,
                     const char *_options_json,
                     FFI_ArrowSchema *result_schema,
                     FFI_ArrowArray *result_array);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RSOD_GO_H */

#ifdef __cplusplus
} // extern "C"
#endif
