name: 'GO Plugin Builder'
description: 'Compiles Go backend for the plugin'

inputs:
  target:
    description: 'Compilation target'
    default: 'x86_64-unknown-linux-gnu'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'
    
    - name: Download Go dependencies
      shell: bash
      run: |
        go install github.com/magefile/mage@latest
        go mod download
    
    - name: Build Go Backend
      shell: bash
      run: mage -v build:linux