name: 'nodejs Plugin Builder'
description: 'Compiles Node.js frontend for the plugin'

runs:
  using: "composite"
  steps:
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    
    - name: copy README.md to dist
      shell: bash
      run: |
        cp -f README.md src/README.md
    
    - name: Build Node.js Frontend
      shell: bash
      run: |
        npm install
        npm run build