name: "Grafana Build Plugin"
description: "Builds a Grafana plugin"

on:
  push:
    tags:
      - 'v*' # Run workflow on version tags, e.g. v1.0.0.

jobs:
  release:
    permissions:
      id-token: write
      contents: write
      attestations: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - 'x86_64-unknown-linux-gnu'
          # - 'aarch64-unknown-linux-gnu'
          # - 'aarch64-apple-darwin'
          # - 'x86_64-pc-windows-gnu'
          # - 'aarch64-pc-windows-gnu'
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Rust Builder
        uses: ./.github/actions/rust-builder
        with:
          target: ${{ matrix.target }}
      
      - name: Run Go Builder
        uses: ./.github/actions/go-builder
        with:
          target: ${{ matrix.target }}
  
      - name: Run Node.js Builder
        uses: ./.github/actions/js-builder

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ibumblebee-alert4ml-datasource-0.1.4.linux_amd64.zip
          path: dist/
          retention-days: 5